### ISSUE TITLE
Consider open-sourcing Katalon Recorder

### ISSUE THREAD

**Issue by pcan** [katalon-studio/katalon-recorder-samples#3]
Hi, I'm currently working on my thesis project and I'm using Katalon recorder for building automated UI tests. The work of my thesis aims to validate a new automated test repair technique and I need some kind of customization of selenium locator builders. Katalon uses xpath and a few others, but it would be great if I could extend the base functionality with my custom locator builders. 
I think Katalon recorder is a great project and I would be very grateful if you plan to make a github project for it.

**Comment by devalex88** [comment]
@pcan,

We've received a number of requests for custom locator builders here https://forum.katalon.com/discussion/4354. We will work on it and get back to you soon. In the meantime, could you please help describe your suggestion in more details (e.g. will your builder return a locator for KR in XPath, CSS, or some custom syntax that only the builder itself can use etc.)?

By the way, your thesis sounds interesting. It would be great if you can share it with us upon completion :).

**Comment by devalex88** [comment]
@pcan,

I hope you are doing well with your thesis.

Custom locator builders have been supported now. Please read more at https://forum.katalon.com/discussion/6286/we-have-released-katalon-recorder-3-5-0-with-support-for-extension-scripts-aka-user-extensions-js.

Thank you again for the suggestion.

**Comment by pcan** [comment]
Oh, sorry for the delay... Thank you so much for releasing this feature :tada:

> In the meantime, could you please help describe your suggestion in more details (e.g. will your builder return a locator for KR in XPath, CSS, or some custom syntax that only the builder itself can use etc.)?

I'm going to write a custom CSS locator builder that looks for a specific class that's injected in the HTML templates by a pre-processor.

> By the way, your thesis sounds interesting. It would be great if you can share it with us upon completion :).

I will share it when ready! Thanks again for your fast response! :smiley:
