### ISSUE TITLE
TestData - storeCSV return seems not correct

### ISSUE THREAD

**Issue by StartleChen** [katalon-studio/katalon-recorder-samples#5]
In TestData test case, it uses storeCsv command: 
storeCsv |    data.csv,1,last    | last

Refer to the reference, it would look for **Row 1**, column "**last**" in file "**data.csv**"
The result is "**Rogers**"

but refer to the csv file, row 1 is the header, so shouldn't it return "**last**"?
or, if it starts from the data row, shouldn't it be "**Smith**"?

**Comment by StartleChen** [comment]
The issue was discussed in another article.
https://forum.katalon.com/discussion/6927/the-loadvars-runs-for-an-extra-csv-row-that-doesnt-exist

**Comment by devalex88** [comment]
Thank you for the report.

Please try this comment https://forum.katalon.com/t/the-loadvars-runs-for-an-extra-csv-row-that-doesnt-exist/11073/2:

> I figured out - somehow the .csv always get the trailing spaces. Not sure if it is a Defect with the Katalon Recorder or what, but if to open .csv file in the editor such as word-pad and clear the trailing spaces - all works fine.

If it does not work, please share a sample test case and a sample CSV to reproduce the issue.
