### ISSUE TITLE
Uploading images with error  - Chrome

### ISSUE THREAD

**Issue by alexandremsouza1** [katalon-studio/katalon-recorder-samples#6]
when trying to send images by command line , appear error below.

[error] {"code":-32000,"message":"Not allowed"}

![image](https://user-images.githubusercontent.com/38253342/53646460-fee85a00-3c19-11e9-9a98-974f5c0d02a1.png)

Configurations:

Katalon recorder 3.6.12
Chrome 72.0.3626.119

**Comment by devalex88** [comment]
Please right-click on the extension icon on the top right toolbar, select Manage extensions. In the Manage extensions page, enable "Allow access to file URLs".

For more details please see https://docs.katalon.com/katalon-recorder/docs/faq-and-troubleshooting-instructions.html#upload-files.
