### ISSUE TITLE
no puedo integrar katalon con jenkins por un error de licencia

### ISSUE THREAD

**Issue by maximilianofni** [katalon-studio/katalon-recorder-samples#7]
no puedo integrar jenkins con katalon pur un error de licencia
![2020-03-12_16-05-29](https://user-images.githubusercontent.com/17895688/76558351-e8571e80-647b-11ea-9413-ef298e689c8a.png)

**Comment by pgroot91** [comment]
You are in the wrong repo. This repo is a collection of examples for the browser extension "katalon recorder" and not Katalon Studio.
